### ISSUE TITLE
scroll-spy green dot not "jumping" between headlines in Sustaining

### ISSUE THREAD

**Issue by martinitschka** [finoradin/mattersinmediart.org#18]
also not working properly in acquisition and assessment

**Comment by finoradin** [comment]
it is because people have made changes to the sections without updating the menus accordingly

**Comment by martinitschka** [comment]
So i did these changes and i adjusted the scrollspy sections and it does
jump to the section when you click on the menu, but the green thingy does
not move down with you as you scroll. this is what i meant with the issue,
saying "green dot not jumping".

best,
Martina
